### ISSUE TITLE
Integration tests fail

### ISSUE THREAD

**Issue by anehx** [html-next/vertical-collection#145]
Hi,

When I run an integration test of a component using `vertical-collection` I always get this error:

```
Error: Attempted to remove a handler from an unknown element or an element with no handlers
```

I was able to reproduce this in a new empty ember app so it's not because of my application. Sadly I couldn't create a twiddle somehow..

**Comment by nragaz** [comment]
This is likely resolved by https://github.com/html-next/vertical-collection/pull/140, but it doesn't seem like that change has been in a release yet.

**Comment by anehx** [comment]
Actually this didn't fix it since I do have `this._scrollHandler`, however `this._scrollContainer` is null..

**Comment by anehx** [comment]
I found the error. In my app I pass `containerSelector` which does not exist while testing. #140 fixes the error in a new application.
